services:
  - type: web
    name: jb-tactics
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true

    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /sw.js
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /manifest.webmanifest
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
